#!/usr/bin/env python

from versions import between, before, after, check, NOT_INSTALLABLE

vectors = [

{
	'id'			: 0,
	'desc'			: 'API.getHeaderLogoUrl was added and changes',
	'related'		: 'module',
	'module'		: 'API',
	'url'			: 'index.php?module=API&method=API.getHeaderLogoUrl',
	'answers'			: [
[ between('0.1', '0.4.3'), 'header field contains', ['set-cookie', 'PHPSESSID='] ],
[ between('0.4.4', '1.5') + between('1.6', '2.2.0') + between('2.2.1-b1', '2.2.1-b3'), 'header field contains', ['set-cookie', 'PIWIK_SESSID='] ],
[between("0.4.2","0.6.3"),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<error message="Piwik_API_API could not be autoloaded." />
</result>'''
],
[between("0.6.4","1.4"),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<error message="The method 'getHeaderLogoUrl' does not exist or is not available in the module 'Piwik_API_API'." />
</result>'''
],
[
between("1.5","1.12"),
'matches',
'''<\?xml version="1.0" encoding="utf-8" \?>
<result>.*/themes/default/images/logo-header.png</result>'''
],
[
"2.0",
'matches',
'''<\?xml version="1.0" encoding="utf-8" \?>
<result>.*/plugins/Zeitgeist/images/logo-header.png</result>'''
],
[
between("2.0.1", "2.1.1-b12") + between("2.1.1-b9", "2.11.2-rc1"),
'matches',
'''<\?xml version="1.0" encoding="utf-8" \?>
<result>.*/plugins/Morpheus/images/logo-header.png</result>'''
],
["2.1.1-b8",
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>plugins/Morpheus/images/logo-header.png</result>'''
],

]},

#################################################################################################################################################################################################################################

{
	'id'			: 1,
	'desc'			: 'API.getIpFromHeader was added',
	'related'		: 'module',
	'module'		: 'API',
	'url'			: 'index.php?module=API&method=API.getIpFromHeader',
	'answers'			: [
[
between("1.0","1.12"),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<error message="The method 'getIpFromHeader' does not exist or is not available in the module 'Piwik_API_API'." />
</result>'''
],
[
between("2.0", "2.4"),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<error message="The method 'getIpFromHeader' does not exist or is not available in the module '\Piwik\Plugins\API\API'." />
</result>'''
],
[
between("2.5", "2.11.0-b2"),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<error message="You can't access this resource as it requires an view access for at least one website." />
</result>'''
]
]
},

#################################################################################################################################################################################################################################

{
  'desc': 'Autogenerated hash matching vector for piwik.js created at (Thu Mar 12 20:11:44 2015)',
  'id': 'piwikjs',
  'related': 'piwik.js',
  'url': 'piwik.js',
  'answers': [[['2.10.0-b9',
                '2.10.0-b6',
                '2.10.0-b5',
                '2.9.1',
                '2.10.0-b1',
                '2.10.0-b7',
                '2.10.0',
                '2.10.0-b3',
                '2.11.0-b2',
                '2.9.1-b2',
                '2.10.0-b11',
                '2.10.0-b8',
                '2.9.1-b1',
                '2.10.0-rc4',
                '2.10.0-b4',
                '2.10.0-rc1',
                '2.10.0-b10',
                '2.10.0-rc3',
                '2.10.0-b2'],
               'hash',
               '2f40d420942f12d5ab8e2b64e62a44ea'],
              [['2.2.0-b18',
                '2.2.0-b14',
                '2.2.0-b15',
                '2.2.0-b13',
                '2.2.0-b16',
                '2.1.1-b12'],
               'hash',
               '5a26dca997cd048c61920ebbd99d00d5'],
              [['0.1.7',
                '0.1.5',
                '0.1.2',
                '0.1.3',
                '0.2.1',
                '0.2.7',
                '0.1.4',
                '0.2.9',
                '0.1.10',
                '0.1.0',
                '0.2.2',
                '0.1.9',
                '0.1.6',
                '0.1.8',
                '0.2.3',
                '0.2.8',
                '0.2.6',
                '0.2.5',
                '0.1.1',
                '0.2.4'],
               'hash',
               '6a62b677e0fa5543226c44435c5d08fa'],
              [['2.2.0-rc1',
                '2.2.1-b2',
                '2.2.0-rc4',
                '2.2.0-rc2',
                '2.2.1-rc1',
                '2.2.1-b3',
                '2.2.1',
                '2.2.0-rc3',
                '2.2.1-b1',
                '2.2.2-b1',
                '2.2.0',
                '2.2.1-b4',
                '2.2.1-rc3',
                '2.2.3-b1',
                '2.2.2'],
               'hash',
               '6e7bb550f0b87029593c66404f477088'],
              [['2.9.0-b3',
                '2.8.3',
                '2.9.0-b8',
                '2.9.0-b5',
                '2.8.1-rc1',
                '2.9.0-rc2',
                '2.8.2',
                '2.8.1',
                '2.9.0-b6',
                '2.9.0-b2',
                '2.8.0',
                '2.9.0-b4',
                '2.8.0-rc2',
                '2.9.0-b7',
                '2.9.0',
                '2.9.0-b1',
                '2.8.1-b1',
                '2.8.1-b2',
                '2.9.0-rc1',
                '2.9.0-b9'],
               'hash',
               'dea49cb63800f80094426e8c08797654'],
              [['2.5.0-b2',
                '2.4.0-rc1',
                '2.4.1',
                '2.4.1-rc1',
                '2.5.0-b1',
                '2.4.0'],
               'hash',
               '173893215430baff0d30c9821bf303e5'],
              [['0.6.0',
                '0.5.5',
                '0.9.0',
                '0.8.0',
                '0.6.4',
                '0.6.2',
                '0.6.1',
                '0.7.0',
                '0.6.3'],
               'hash',
               '9f9ddede4f3d75b315d7aebaafecc300'],
              [['2.11.2-b2'], 'hash', '3f81ba599a1e66cc650cd45b56744181'],
              [['2.7.0-b3'], 'hash', '3f40d57d89583fb98cff067b87616c57'],
              [['2.3.0-rc3',
                '2.3.0-rc2',
                '2.4.0-b3',
                '2.3.0-rc4',
                '2.4.0-b5',
                '2.4.0-b2',
                '2.3.0-rc1',
                '2.3.0',
                '2.2.3-b7'],
               'hash',
               '7f1f78c74657f3b3177809c8f1b2d18a'],
              [['0.9.9', '1.0.0'],
               'hash',
               '94d21a85f6892c7116feee3b5eada824'],
              [['1.11.0', '1.11.1'],
               'hash',
               '3323c01b46de2b042f8bc5a0f5f9ccca'],
              [['1.7.1', '1.7.0'],
               'hash',
               '4bf8fed1136557cb0074ed7d2127a8d8'],
              [['2.5.0-b3'], 'hash', '0e6804980916d47a69e6819e9ad9674a'],
              [['1.8.0', '1.8.1', '1.8.2'],
               'hash',
               '2d45ae0d02da8005ec644bd679043d79'],
              [['2.0.0', '2.0.3', '2.0.2', '2.0.1'],
               'hash',
               'bd552ec898371660b514ace4e843827c'],
              [['0.2.29', '0.2.30'],
               'hash',
               'd16507853dcd149f6a1a3148ca3de465'],
              [['2.5.0-rc1',
                '2.7.0-b1',
                '2.6.0-rc3',
                '2.6.0-rc2',
                '2.6.0',
                '2.6.0-rc1',
                '2.6.0-rc4',
                '2.5.0-rc3',
                '2.5.0',
                '2.6.0-b1',
                '2.6.1',
                '2.5.0-rc4',
                '2.6.1-b1'],
               'hash',
               '408930f8766e284569e65bdd331b6ff9'],
              [['1.2.0'], 'hash', '469eadd1d5abfbe10640de25665c7383'],
              [['0.5.3', '0.5.2', '0.5.0', '0.5.1', '0.5.4'],
               'hash',
               'bbc89206425a94753d4be6b2fffd5785'],
              [['2.11.2', '2.11.2-b3', '2.11.2-rc1'],
               'hash',
               'dae28b979fbe6c7bd6819079a0432a41'],
              [['2.11.0-b4'], 'hash', 'be9c9f2901898e6a284f72d5f337deba'],
              [['0.2.37', '0.2.35', '0.2.36'],
               'hash',
               'e22ab83d24c1cf75d214b18bcfdcb213'],
              [['2.8.0-rc1', '2.8.0-b2', '2.8.0-b3'],
               'hash',
               'eff112d89fef7ca881d3c42c45defb74'],
              [['0.4.0'], 'hash', 'eb38e858cad2c3ba1b8113756c9ce4af'],
              [['1.8.4', '1.8.3'],
               'hash',
               '20b3926f6139b18b3bc888c87512859c'],
              [['0.2.10', '0.2.11'],
               'hash',
               '19df02244f7523853a5afa93afc6424d'],
              [['1.9.1'], 'hash', '7b7d044758c9f6852b5880373be810b3'],
              [['0.2.28',
                '0.2.13',
                '0.2.18',
                '0.2.23',
                '0.2.17',
                '0.2.12',
                '0.2.16',
                '0.2.27',
                '0.2.26',
                '0.2.20',
                '0.2.14',
                '0.2.22',
                '0.2.19',
                '0.2.25',
                '0.2.24'],
               'hash',
               'aa8a49da2b27c26fd63c5f1779bc8479'],
              [['1.5.0', '1.5.1'],
               'hash',
               'f95fe694a25ecf19ad4c1519c1d29445'],
              [['0.2.33'], 'hash', '0dcd472012871df1fcf628ccecd91c4d'],
              [['0.4.2', '0.4.3'],
               'hash',
               'd628b25103dc83736876163b2c201ed6'],
              [['2.1.1-b9', '2.1.1-b8', '2.1.1-b10'],
               'hash',
               'f91a294835fa279755868f750b404257'],
              [['2.7.0', '2.7.0-rc1', '2.7.0-rc2'],
               'hash',
               '32e9f7d63fb3b53e5da87f995c217d68'],
              [['2.4.0-b8'], 'hash', 'b7625563e76c44cb1503d3e32ce1e724'],
              [['1.6.0'], 'hash', 'd45710bd2e1f5a6560810e3158464fb3'],
              [['0.4.1'], 'hash', '94494dc92fe6bc10a1fae9b540584df9'],
              [['1.9.2'], 'hash', '71fc848887b176debd9a8ebb7c83e7cb'],
              [['1.1.1', '1.1.0'],
               'hash',
               'f2e1269798c32d0ac9fca524b3554a1d'],
              [['2.2.3-b4'], 'hash', 'b1ecd5cf4b38926ce7221a39f4bd3204'],
              [['2.11.1-rc1',
                '2.11.0-rc1',
                '2.11.0',
                '2.11.1-b3',
                '2.11.1-b1',
                '2.11.1'],
               'hash',
               '2173ad4d695b9a50a75370e598ffb89f'],
              [['2.1.0'], 'hash', '5ec4779175496689d2e2ac97ffd2fe16'],
              [['2.2.3-b6'], 'hash', '7d85190591fc88cddcc999af7ce0b987'],
              [['0.4.5', '0.4.4'],
               'hash',
               'dc6d31b099f5616c27579d138fa84553'],
              [['0.2.34'], 'hash', '231b1d87d902ea6ae7ede07139dda949'],
              [['1.10.1', '1.10.0'],
               'hash',
               '52806e66490db3a38c2c8bfc86e254e4'],
              [['1.12.0'], 'hash', 'ab81c375bb10b2245dcdb8ed3ba933c0'],
              [['1.9.0'], 'hash', '786f3f3b18121c80dcfa05a25904c7eb'],
              [['1.4.0'], 'hash', 'ee1ccef2cd03eefe5df8fdefed8116a7'],
              [['2.11.2-b1'], 'hash', 'f66077f70cc9aeb19b3b7955d452a316'],
              [['2.11.0-b6', '2.11.0-b5'],
               'hash',
               'fcc59d691dc7625916f30238a2ee0386'],
              [['0.2.32', '0.2.31'],
               'hash',
               'f2dff1182732a3ae717acf16c6b59be7'],
              [['2.7.0-b4'], 'hash', '9ed177af9d017c7216b0c66923fb6dee'],
              [['2.4.0-b6'], 'hash', 'bf9af5b2066e3c329fd40ad1fa0f7121'],
              [['2.11.0-b7'], 'hash', '75245e627e56fa0aba977e2d5b16ae2a'],
              [['2.11.0-b3'], 'hash', 'b47036e45baae114e464804dda13ca48'],
              [['2.4.0-b7'], 'hash', 'bd15da1c42c8622fcd45d456d1d5edaf'],
              [['1.3.0'], 'hash', '8053db1521b9268c73b830a3b02c7d9d'],
              [['1.2.1'], 'hash', '1be7880b6adb13c09c4f96e16b6d8fdc']
	],
},

#################################################################################################################################################################################################################################

{
	'id'			: 3,
	'desc'			: 'The Tracker API can send an empty 204 response instead of 200 with an 1px gif',
	'related'		: 'header',
	'url'			: 'piwik.php?idsite=1&rec=1&url=a&send_image=0',
	'answers'			: [
# [ before("2.9"), 'status', 200 ],
# [ after("2.9.1"), 'status', 204 ]
]
},


{
	'id'			: 1001,
	'desc'			: 'Check the Tracker API "piwik.php": invalid site id=9999999999 and recording flag set',
	'url'			: 'piwik.php?idsite=9999999999&rec=1&url=a&send_image=0',
	'unjudgeable'	: NOT_INSTALLABLE,
	'answers'			: [
[ between('0.4.2', '0.5.5') + between('0.6.4','1.1.1'), 'header field equals', ['p3p',"CP='OTI DSP COR NID STP UNI OTPa OUR'"] ],
[ between('0.4.2', '0.5.5') + between('0.6.4','0.7'), 'header field contains', ['set-cookie', 'piwik_visitor9999999999'] ],
[ between('0.8','1.1.1'), 'header field contains', ['set-cookie', 'piwik_visitor=9999999999'] ],
# TODO: the content type in headers changed!
[ between('0.4.2', '0.5.5') + between('0.6.4','1.2.1') + between('1.8.3', '2.9.0-rc2'), 'equals', "GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;"],
[ between('1.3', '1.8.2'), 'contains', "<p>The requested website id = 9999999999 couldn't be found</p><p>Edit the following line in piwik.php to enable tracker debugging and display a backtrace:</p>" ],
[ between('0.6','0.6.3') + between('1.3','1.12') + between('1.3','1.12') + between('2.9.1','2.11.2-rc1'), 'header field equals', ['vary','Accept-Encoding'] ],
[ between('0.4.2','0.5.5') + between('0.6.4', '2.4.1-rc1') + between('2.5.0-b1','2.5.0-b3'), 'status', 200 ],
[ between('0.6', '0.6.3') + ['2.5.0'] + between('2.5.0-rc1', '2.9.0-rc2'), 'status', 500 ],
[ between('2.9.1', '2.11.2-rc1'), 'status', 204 ],
]
},

#################################################################################################################################################################################################################################

{
	'id'			: 1002,
	'desc'			: 'Check the Tracker API "piwik.php": invalid site id=0',
	'url'			: 'piwik.php?idsite=0',
	'unjudgeable'	: NOT_INSTALLABLE,
	'answers'			: [
[ between('0.4.2', '1.0') + ['2.5.0'] + between('2.5.0-rc1','2.9.0-rc2'), 'status', 500 ],
[ between('1.1','2.4.1-rc1') + between('2.5.0-b1','2.5.0-b3'), 'status', 200 ],
[ between('2.9.1','2.11.2-rc1'), 'status', 400],
[ between('0.4.2', '1.0'), 'equals', ''],
[ between('1.8.3', '2.9.1-b2') + between('2.10.0-b1', '2.10.0-b3'), 'equals', "GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;"],
[ ['2.10.0'] + between('2.10.0-b4', '2.11.2-rc1'), 'equals', "GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;<a href='/'>Piwik</a> is a free/libre web <a href='http://piwik.org'>analytics</a> that lets you keep control of your data." ],
[ between('0.4.2','1.0'), 'header field equals', [ 'content-type', 'text/html' ]],
[ between('1.1','1.12'), 'header field equals', [ 'content-type', 'text/html; charset=utf-8']],
[ between('2.0','2.11.2-rc1'), 'header field equals', [ 'content-type', 'image/gif']],
[ between('0.4.2', '1.12'), 'header field equals', ['vary', 'Accept-Encoding'] ],
[ between('1.1','1.1.1'), 'contains', '<p>Invalid idsite: 0</p><p>Edit the following line in piwik.php to enable tracker debugging and display a backtrace:</p>'],
[ between('1.2','1.8.2'), 'contains', '<p>Invalid idSite</p><p>Edit the following line in piwik.php to enable tracker debugging and display a backtrace:</p>'],
[ between('1.8','1.8.2'), 'contains', '<body id="simple">'],
[ between('1.6','1.7.1'), 'contains', '<body>\n<div id="contentsimple">'],
[ between('1.1','1.2.1'), 'contains', '# open source web analytics</span></div>'],
[ between('1.3','1.7.1'), 'contains', "# <a href='http://piwik.org/'>web analytics</a></span></div>"],
[ between('1.8','1.8.2'), 'contains', "# <a href='http://piwik.org/'>Web Analytics</a></span></div>"], # case changed!
]
},

#################################################################################################################################################################################################################################

{
	'id'			: 1003,
	'desc'			: 'Check the Tracker API "piwik.php": invalid site id=0',
	'url'			: '',
#	'unjudgeable'	: NOT_INSTALLABLE,
	'answers'			: [
[
between('1.8.2','1.9.2'),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entereing here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entereing here</entry_sum_visit_length>
	</row>
</result>'''
],
[
between('1.10','2.1.1-b9') + between('2.2.0-b13', '2.2.0-b18'),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entering here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entering here</entry_sum_visit_length>
	</row>
</result>'''
],
[
['2.2.0'] + between('2.2.0-rc1', '2.4.1-rc1'),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entering here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entering here</entry_sum_visit_length>
		<nb_events>Total events</nb_events>
		<sum_event_value>Total value</sum_event_value>
		<min_event_value>Minimum value</min_event_value>
		<max_event_value>Maximum value</max_event_value>
		<avg_event_value>Average value</avg_event_value>
		<nb_events_with_value>Events with a value</nb_events_with_value>
	</row>
</result>'''
],
[
between('2.5.0','2.6.1-b1'),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entering here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entering here</entry_sum_visit_length>
		<nb_pageviews>Pageviews</nb_pageviews>
		<nb_uniq_pageviews>Unique Pageviews</nb_uniq_pageviews>
		<nb_downloads>Downloads</nb_downloads>
		<nb_uniq_downloads>Unique Downloads</nb_uniq_downloads>
		<nb_outlinks>Outlinks</nb_outlinks>
		<nb_uniq_outlinks>Unique Outlinks</nb_uniq_outlinks>
		<nb_searches>Searches</nb_searches>
		<nb_keywords>Unique Keywords</nb_keywords>
		<avg_time_generation>Avg. generation time</avg_time_generation>
		<nb_pages_per_search>Search Results pages</nb_pages_per_search>
		<nb_hits_following_search>Clicked in search results</nb_hits_following_search>
		<visits_evolution>Visits Evolution</visits_evolution>
		<actions_evolution>Actions Evolution</actions_evolution>
		<pageviews_evolution>Pageviews Evolution</pageviews_evolution>
		<revenue_evolution>Revenue Evolution</revenue_evolution>
		<nb_conversions_evolution>Conversions Evolution</nb_conversions_evolution>
		<orders_evolution>Ecommerce Orders Evolution</orders_evolution>
		<ecommerce_revenue_evolution>Product Revenue Evolution</ecommerce_revenue_evolution>
		<nb_visits_percentage>% Visits</nb_visits_percentage>
		<orders>Ecommerce Orders</orders>
		<ecommerce_revenue>Product Revenue</ecommerce_revenue>
		<revenue_per_visit>Revenue per Visit</revenue_per_visit>
		<quantity>Quantity</quantity>
		<avg_price>Average Price</avg_price>
		<avg_quantity>Average Quantity</avg_quantity>
		<revenue_subtotal>Subtotal</revenue_subtotal>
		<revenue_tax>Tax</revenue_tax>
		<revenue_shipping>Shipping</revenue_shipping>
		<revenue_discount>Discount</revenue_discount>
		<avg_order_revenue>Average Order Value</avg_order_revenue>
		<nb_events>Total events</nb_events>
		<sum_event_value>Total value</sum_event_value>
		<min_event_value>Minimum value</min_event_value>
		<max_event_value>Maximum value</max_event_value>
		<avg_event_value>Average value</avg_event_value>
		<nb_events_with_value>Events with a value</nb_events_with_value>
		<nb_visits_returning>Returning Visits</nb_visits_returning>
		<nb_actions_returning>Actions by Returning Visits</nb_actions_returning>
		<avg_time_on_site_returning>Avg. Duration of a Returning Visit (in sec)</avg_time_on_site_returning>
		<bounce_rate_returning>Bounce Rate for Returning Visits</bounce_rate_returning>
		<nb_actions_per_visit_returning>Avg. Actions per Returning Visit</nb_actions_per_visit_returning>
		<nb_uniq_visitors_returning>Unique returning visitors</nb_uniq_visitors_returning>
	</row>
</result>'''
],
[
['2.7.0'] + between('2.7.0-b3', '2.8.3'),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_users>Users</nb_users>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_nb_users>Users (daily sum)</sum_daily_nb_users>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entering here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entering here</entry_sum_visit_length>
		<nb_pageviews>Pageviews</nb_pageviews>
		<nb_uniq_pageviews>Unique Pageviews</nb_uniq_pageviews>
		<nb_downloads>Downloads</nb_downloads>
		<nb_uniq_downloads>Unique Downloads</nb_uniq_downloads>
		<nb_outlinks>Outlinks</nb_outlinks>
		<nb_uniq_outlinks>Unique Outlinks</nb_uniq_outlinks>
		<nb_searches>Searches</nb_searches>
		<nb_keywords>Unique Keywords</nb_keywords>
		<avg_time_generation>Avg. generation time</avg_time_generation>
		<nb_pages_per_search>Search Results pages</nb_pages_per_search>
		<nb_hits_following_search>Clicked in search results</nb_hits_following_search>
		<visits_evolution>Visits Evolution</visits_evolution>
		<actions_evolution>Actions Evolution</actions_evolution>
		<pageviews_evolution>Pageviews Evolution</pageviews_evolution>
		<revenue_evolution>Revenue Evolution</revenue_evolution>
		<nb_conversions_evolution>Conversions Evolution</nb_conversions_evolution>
		<orders_evolution>Ecommerce Orders Evolution</orders_evolution>
		<ecommerce_revenue_evolution>Product Revenue Evolution</ecommerce_revenue_evolution>
		<nb_visits_percentage>% Visits</nb_visits_percentage>
		<orders>Ecommerce Orders</orders>
		<ecommerce_revenue>Product Revenue</ecommerce_revenue>
		<revenue_per_visit>Revenue per Visit</revenue_per_visit>
		<quantity>Quantity</quantity>
		<avg_price>Average Price</avg_price>
		<avg_quantity>Average Quantity</avg_quantity>
		<revenue_subtotal>Subtotal</revenue_subtotal>
		<revenue_tax>Tax</revenue_tax>
		<revenue_shipping>Shipping</revenue_shipping>
		<revenue_discount>Discount</revenue_discount>
		<avg_order_revenue>Average Order Value</avg_order_revenue>
		<nb_events>Total events</nb_events>
		<sum_event_value>Total value</sum_event_value>
		<min_event_value>Minimum value</min_event_value>
		<max_event_value>Maximum value</max_event_value>
		<avg_event_value>Average value</avg_event_value>
		<nb_events_with_value>Events with a value</nb_events_with_value>
		<nb_visits_returning>Returning Visits</nb_visits_returning>
		<nb_actions_returning>Actions by Returning Visits</nb_actions_returning>
		<avg_time_on_site_returning>Avg. Duration of a Returning Visit (in sec)</avg_time_on_site_returning>
		<bounce_rate_returning>Bounce Rate for Returning Visits</bounce_rate_returning>
		<nb_actions_per_visit_returning>Avg. Actions per Returning Visit</nb_actions_per_visit_returning>
		<nb_uniq_visitors_returning>Unique returning visitors</nb_uniq_visitors_returning>
		<nb_impressions>Impressions</nb_impressions>
		<nb_interactions>Interactions</nb_interactions>
		<interaction_rate>Interaction Rate</interaction_rate>
	</row>
</result>'''
],
[
['2.7.0-b1'],
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entering here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entering here</entry_sum_visit_length>
		<nb_pageviews>Pageviews</nb_pageviews>
		<nb_uniq_pageviews>Unique Pageviews</nb_uniq_pageviews>
		<nb_downloads>Downloads</nb_downloads>
		<nb_uniq_downloads>Unique Downloads</nb_uniq_downloads>
		<nb_outlinks>Outlinks</nb_outlinks>
		<nb_uniq_outlinks>Unique Outlinks</nb_uniq_outlinks>
		<nb_searches>Searches</nb_searches>
		<nb_keywords>Unique Keywords</nb_keywords>
		<avg_time_generation>Avg. generation time</avg_time_generation>
		<nb_pages_per_search>Search Results pages</nb_pages_per_search>
		<nb_hits_following_search>Clicked in search results</nb_hits_following_search>
		<visits_evolution>Visits Evolution</visits_evolution>
		<actions_evolution>Actions Evolution</actions_evolution>
		<pageviews_evolution>Pageviews Evolution</pageviews_evolution>
		<revenue_evolution>Revenue Evolution</revenue_evolution>
		<nb_conversions_evolution>Conversions Evolution</nb_conversions_evolution>
		<orders_evolution>Ecommerce Orders Evolution</orders_evolution>
		<ecommerce_revenue_evolution>Product Revenue Evolution</ecommerce_revenue_evolution>
		<nb_visits_percentage>% Visits</nb_visits_percentage>
		<orders>Ecommerce Orders</orders>
		<ecommerce_revenue>Product Revenue</ecommerce_revenue>
		<revenue_per_visit>Revenue per Visit</revenue_per_visit>
		<quantity>Quantity</quantity>
		<avg_price>Average Price</avg_price>
		<avg_quantity>Average Quantity</avg_quantity>
		<revenue_subtotal>Subtotal</revenue_subtotal>
		<revenue_tax>Tax</revenue_tax>
		<revenue_shipping>Shipping</revenue_shipping>
		<revenue_discount>Discount</revenue_discount>
		<avg_order_revenue>Average Order Value</avg_order_revenue>
		<nb_events>Total events</nb_events>
		<sum_event_value>Total value</sum_event_value>
		<min_event_value>Minimum value</min_event_value>
		<max_event_value>Maximum value</max_event_value>
		<avg_event_value>Average value</avg_event_value>
		<nb_events_with_value>Events with a value</nb_events_with_value>
		<nb_visits_returning>Returning Visits</nb_visits_returning>
		<nb_actions_returning>Actions by Returning Visits</nb_actions_returning>
		<avg_time_on_site_returning>Avg. Duration of a Returning Visit (in sec)</avg_time_on_site_returning>
		<bounce_rate_returning>Bounce Rate for Returning Visits</bounce_rate_returning>
		<nb_actions_per_visit_returning>Avg. Actions per Returning Visit</nb_actions_per_visit_returning>
		<nb_uniq_visitors_returning>Unique returning visitors</nb_uniq_visitors_returning>
	</row>
</result>'''
],
[
between('2.9.0', '2.10.0-rc4') + between('2.11.0-b2', '2.11.0-b3'),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_users>Users</nb_users>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_nb_users>Users (daily sum)</sum_daily_nb_users>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entering here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entering here</entry_sum_visit_length>
		<nb_pageviews>Pageviews</nb_pageviews>
		<nb_uniq_pageviews>Unique Pageviews</nb_uniq_pageviews>
		<nb_downloads>Downloads</nb_downloads>
		<nb_uniq_downloads>Unique Downloads</nb_uniq_downloads>
		<nb_outlinks>Outlinks</nb_outlinks>
		<nb_uniq_outlinks>Unique Outlinks</nb_uniq_outlinks>
		<nb_searches>Searches</nb_searches>
		<nb_keywords>Unique Keywords</nb_keywords>
		<avg_time_generation>Avg. generation time</avg_time_generation>
		<nb_pages_per_search>Search Results pages</nb_pages_per_search>
		<nb_hits_following_search>Clicked in search results</nb_hits_following_search>
		<visits_evolution>Visits Evolution</visits_evolution>
		<actions_evolution>Actions Evolution</actions_evolution>
		<pageviews_evolution>Pageviews Evolution</pageviews_evolution>
		<revenue_evolution>Revenue Evolution</revenue_evolution>
		<nb_conversions_evolution>Conversions Evolution</nb_conversions_evolution>
		<orders_evolution>Ecommerce Orders Evolution</orders_evolution>
		<ecommerce_revenue_evolution>Product Revenue Evolution</ecommerce_revenue_evolution>
		<nb_visits_percentage>% Visits</nb_visits_percentage>
		<orders>Ecommerce Orders</orders>
		<ecommerce_revenue>Product Revenue</ecommerce_revenue>
		<revenue_per_visit>Revenue per Visit</revenue_per_visit>
		<quantity>Quantity</quantity>
		<avg_price>Average Price</avg_price>
		<avg_quantity>Average Quantity</avg_quantity>
		<revenue_subtotal>Subtotal</revenue_subtotal>
		<revenue_tax>Tax</revenue_tax>
		<revenue_shipping>Shipping</revenue_shipping>
		<revenue_discount>Discount</revenue_discount>
		<avg_order_revenue>Average Order Value</avg_order_revenue>
		<nb_events>Total events</nb_events>
		<sum_event_value>Total value</sum_event_value>
		<min_event_value>Minimum value</min_event_value>
		<max_event_value>Maximum value</max_event_value>
		<avg_event_value>Average value</avg_event_value>
		<nb_events_with_value>Events with a value</nb_events_with_value>
		<nb_visits_returning>Returning Visits</nb_visits_returning>
		<nb_actions_returning>Actions by Returning Visits</nb_actions_returning>
		<avg_time_on_site_returning>Avg. Duration of a Returning Visit (in sec)</avg_time_on_site_returning>
		<bounce_rate_returning>Bounce Rate for Returning Visits</bounce_rate_returning>
		<nb_actions_per_visit_returning>Avg. Actions per Returning Visit</nb_actions_per_visit_returning>
		<nb_uniq_visitors_returning>Unique returning visitors</nb_uniq_visitors_returning>
		<nb_users_returning>Returning Users</nb_users_returning>
		<nb_impressions>Impressions</nb_impressions>
		<nb_interactions>Interactions</nb_interactions>
		<interaction_rate>Interaction Rate</interaction_rate>
	</row>
</result>'''
],
[
['2.11.0'] + between('2.11.0-b4','2.11.2-rc1'),
'equals',
'''<?xml version="1.0" encoding="utf-8" ?>
<result>
	<row>
		<nb_visits>Visits</nb_visits>
		<nb_uniq_visitors>Unique visitors</nb_uniq_visitors>
		<nb_actions>Actions</nb_actions>
		<nb_users>Users</nb_users>
		<nb_actions_per_visit>Actions per Visit</nb_actions_per_visit>
		<avg_time_on_site>Avg. Time on Website</avg_time_on_site>
		<bounce_rate>Bounce Rate</bounce_rate>
		<conversion_rate>Conversion Rate</conversion_rate>
		<label>Label</label>
		<date>Date</date>
		<avg_time_on_page>Avg. time on page</avg_time_on_page>
		<sum_time_spent>Total time spent by visitors (in seconds)</sum_time_spent>
		<sum_visit_length>Total time spent by visitors (in seconds)</sum_visit_length>
		<bounce_count>Bounces</bounce_count>
		<bounce_count_returning>Bounce Count for Returning Visits</bounce_count_returning>
		<max_actions>Maximum actions in one visit</max_actions>
		<max_actions_returning>Maximum actions in one returning visit</max_actions_returning>
		<nb_visits_converted_returning>Number of converted returning visits</nb_visits_converted_returning>
		<sum_visit_length_returning>Total time spent by returning visitors (in seconds)</sum_visit_length_returning>
		<nb_visits_converted>Visits with Conversions</nb_visits_converted>
		<nb_conversions>Conversions</nb_conversions>
		<revenue>Revenue</revenue>
		<nb_hits>Pageviews</nb_hits>
		<entry_nb_visits>Entrances</entry_nb_visits>
		<entry_nb_uniq_visitors>Unique entrances</entry_nb_uniq_visitors>
		<exit_nb_visits>Exits</exit_nb_visits>
		<exit_nb_uniq_visitors>Unique exits</exit_nb_uniq_visitors>
		<entry_bounce_count>Bounces</entry_bounce_count>
		<exit_bounce_count>Bounces</exit_bounce_count>
		<exit_rate>Exit rate</exit_rate>
		<sum_daily_nb_uniq_visitors>Unique visitors (daily sum)</sum_daily_nb_uniq_visitors>
		<sum_daily_nb_users>Users (daily sum)</sum_daily_nb_users>
		<sum_daily_entry_nb_uniq_visitors>Unique entrances (daily sum)</sum_daily_entry_nb_uniq_visitors>
		<sum_daily_exit_nb_uniq_visitors>Unique exits (daily sum)</sum_daily_exit_nb_uniq_visitors>
		<entry_nb_actions>Actions after entering here</entry_nb_actions>
		<entry_sum_visit_length>Total time spent by visitors (in seconds) after entering here</entry_sum_visit_length>
		<nb_pageviews>Pageviews</nb_pageviews>
		<nb_uniq_pageviews>Unique Pageviews</nb_uniq_pageviews>
		<nb_downloads>Downloads</nb_downloads>
		<nb_uniq_downloads>Unique Downloads</nb_uniq_downloads>
		<nb_outlinks>Outlinks</nb_outlinks>
		<nb_uniq_outlinks>Unique Outlinks</nb_uniq_outlinks>
		<nb_searches>Searches</nb_searches>
		<nb_keywords>Unique Keywords</nb_keywords>
		<avg_time_generation>Avg. generation time</avg_time_generation>
		<nb_pages_per_search>Search Results pages</nb_pages_per_search>
		<nb_hits_following_search>Clicked in search results</nb_hits_following_search>
		<visits_evolution>Visits Evolution</visits_evolution>
		<actions_evolution>Actions Evolution</actions_evolution>
		<pageviews_evolution>Pageviews Evolution</pageviews_evolution>
		<revenue_evolution>Revenue Evolution</revenue_evolution>
		<nb_conversions_evolution>Conversions Evolution</nb_conversions_evolution>
		<orders_evolution>Ecommerce Orders Evolution</orders_evolution>
		<ecommerce_revenue_evolution>Product Revenue Evolution</ecommerce_revenue_evolution>
		<orders>Ecommerce Orders</orders>
		<ecommerce_revenue>Product Revenue</ecommerce_revenue>
		<revenue_per_visit>Revenue per Visit</revenue_per_visit>
		<quantity>Quantity</quantity>
		<avg_price>Average Price</avg_price>
		<avg_quantity>Average Quantity</avg_quantity>
		<revenue_subtotal>Subtotal</revenue_subtotal>
		<revenue_tax>Tax</revenue_tax>
		<revenue_shipping>Shipping</revenue_shipping>
		<revenue_discount>Discount</revenue_discount>
		<avg_order_revenue>Average Order Value</avg_order_revenue>
		<nb_events>Total events</nb_events>
		<sum_event_value>Total value</sum_event_value>
		<min_event_value>Minimum value</min_event_value>
		<max_event_value>Maximum value</max_event_value>
		<avg_event_value>Average value</avg_event_value>
		<nb_events_with_value>Events with a value</nb_events_with_value>
		<nb_visits_returning>Returning Visits</nb_visits_returning>
		<nb_actions_returning>Actions by Returning Visits</nb_actions_returning>
		<avg_time_on_site_returning>Avg. Duration of a Returning Visit (in sec)</avg_time_on_site_returning>
		<bounce_rate_returning>Bounce Rate for Returning Visits</bounce_rate_returning>
		<nb_actions_per_visit_returning>Avg. Actions per Returning Visit</nb_actions_per_visit_returning>
		<nb_uniq_visitors_returning>Unique returning visitors</nb_uniq_visitors_returning>
		<nb_users_returning>Returning Users</nb_users_returning>
		<nb_impressions>Impressions</nb_impressions>
		<nb_interactions>Interactions</nb_interactions>
		<interaction_rate>Interaction Rate</interaction_rate>
		<nb_visits_percentage>% Visits</nb_visits_percentage>
	</row>
</result>'''
],
]
},
#################################################################################################################################################################################################################################

]

def by_id(search_id):
	for v in vectors:
		if str(v['id']) == str(search_id):
			return v

if __name__ == "__main__":
	import pprint
	pprint.pprint(vectors)
	# check for duplicate ids:
	ids = []
	for v in vectors:
		i = v['id']
		if i in ids:
			print("id %s is duplicate"%i)
		else:
			ids.append(i)
